.MODEL SMALL
.STACK 100H
.DATA
.CODE

MAIN PROC   
          
    MOV BL,7        ; MOVING A NUMBER IN BL REGISTER
         
    MOV AH,2        ; DEFINING PRINT FUNCTION
    MOV DL,BL       ; PRINTS VALUE OF BL IN ASCII VALUE
    ADD DL,48       ; CONVERTING INTO DECIMAL
    INT 21H         ; INTERRURPT PROCEDURE
    
    EXIT:			; BLOCK OF EXIT CODE
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN